<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[dishes added to cart successfully]]>
    </line>
    <line>
      <![CDATA[order has been placed successfully]]>
    </line>
    <line>
      <![CDATA[dishes added to cart successfully]]>
    </line>
    <line>
      <![CDATA[order has been placed successfully]]>
    </line>
    <line>
      <![CDATA[dishes added to cart successfully]]>
    </line>
    <line>
      <![CDATA[order has been placed successfully]]>
    </line>
    <line>
      <![CDATA[dishes added to cart successfully]]>
    </line>
    <line>
      <![CDATA[order has been placed successfully]]>
    </line>
  </reporter-output>
  <suite started-at="2023-08-09T17:57:33 IST" name="Suite" finished-at="2023-08-09T17:58:57 IST" duration-ms="84354">
    <groups>
    </groups>
    <test started-at="2023-08-09T17:57:33 IST" name="Test" finished-at="2023-08-09T17:58:57 IST" duration-ms="84354">
      <class name="user_module.MyOrderTest">
        <test-method is-config="true" signature="config_BC()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:57:33 IST" name="config_BC" finished-at="2023-08-09T17:57:43 IST" duration-ms="10407" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BC -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:57:43 IST" name="config_BM" finished-at="2023-08-09T17:58:20 IST" duration-ms="36748" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="myOrderTest()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:20 IST" name="myOrderTest" finished-at="2023-08-09T17:58:34 IST" duration-ms="13473" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at user_module.MyOrderTest.myOrderTest(MyOrderTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[dishes added to cart successfully]]>
            </line>
            <line>
              <![CDATA[order has been placed successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- myOrderTest -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:34 IST" name="config_AM" finished-at="2023-08-09T17:58:34 IST" duration-ms="339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:34 IST" name="config_BM" finished-at="2023-08-09T17:58:37 IST" duration-ms="2708" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="myOrderTest()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:37 IST" name="myOrderTest" finished-at="2023-08-09T17:58:42 IST" duration-ms="5151" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at user_module.MyOrderTest.myOrderTest(MyOrderTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[dishes added to cart successfully]]>
            </line>
            <line>
              <![CDATA[order has been placed successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- myOrderTest -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:42 IST" name="config_AM" finished-at="2023-08-09T17:58:42 IST" duration-ms="548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:42 IST" name="config_BM" finished-at="2023-08-09T17:58:44 IST" duration-ms="1426" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="myOrderTest()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:44 IST" name="myOrderTest" finished-at="2023-08-09T17:58:49 IST" duration-ms="4761" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at user_module.MyOrderTest.myOrderTest(MyOrderTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[dishes added to cart successfully]]>
            </line>
            <line>
              <![CDATA[order has been placed successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- myOrderTest -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:49 IST" name="config_AM" finished-at="2023-08-09T17:58:49 IST" duration-ms="340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:49 IST" name="config_BM" finished-at="2023-08-09T17:58:51 IST" duration-ms="2457" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method signature="myOrderTest()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:51 IST" name="myOrderTest" finished-at="2023-08-09T17:58:56 IST" duration-ms="4484" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at user_module.MyOrderTest.myOrderTest(MyOrderTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[dishes added to cart successfully]]>
            </line>
            <line>
              <![CDATA[order has been placed successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- myOrderTest -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:56 IST" name="config_AM" finished-at="2023-08-09T17:58:56 IST" duration-ms="213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_AC()[pri:0, instance:user_module.MyOrderTest@543588e6]" started-at="2023-08-09T17:58:56 IST" name="config_AC" finished-at="2023-08-09T17:58:57 IST" duration-ms="1187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AC -->
      </class> <!-- user_module.MyOrderTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
