<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-AG0407A" failures="1" tests="4" name="user_module.MyOrderTest" time="72.648" errors="0" timestamp="2023-08-09T17:58:58 IST" skipped="3">
  <testcase classname="user_module.MyOrderTest" name="myOrderTest" time="8.198">
    <skipped/>
  </testcase> <!-- myOrderTest -->
  <system-out>
    <![CDATA[dishes added to cart successfully
order has been placed successfully]]>
  </system-out>
  <testcase classname="user_module.MyOrderTest" name="myOrderTest" time="7.558">
    <skipped/>
  </testcase> <!-- myOrderTest -->
  <system-out>
    <![CDATA[dishes added to cart successfully
order has been placed successfully]]>
  </system-out>
  <testcase classname="user_module.MyOrderTest" name="myOrderTest" time="41.780">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at user_module.MyOrderTest.myOrderTest(MyOrderTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
    </failure>
  </testcase> <!-- myOrderTest -->
  <system-out>
    <![CDATA[dishes added to cart successfully
order has been placed successfully]]>
  </system-out>
  <testcase classname="user_module.MyOrderTest" name="myOrderTest" time="15.112">
    <skipped/>
  </testcase> <!-- myOrderTest -->
  <system-out>
    <![CDATA[dishes added to cart successfully
order has been placed successfully]]>
  </system-out>
</testsuite> <!-- user_module.MyOrderTest -->
